# Generated by Django 2.1.5 on 2019-07-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='pub',
        ),
    ]
