# Generated by Django 2.2.7 on 2019-12-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_review', '0003_auto_20190713_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/uploads')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
