# Generated by Django 2.2.1 on 2019-07-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/polls_app/question_pics'),
        ),
    ]
