# Generated by Django 2.1.5 on 2019-07-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0004_question_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
    ]
